### ISSUE TITLE
pcxn gene members error

### ISSUE THREAD

**Issue by ssamberkar** [hidelab/R-packages#1]
To retrieve the genes from a geneset, I used the function - `pcxn.gene_members("Alzheimer's disease (KEGG)")`

which gives the following error - `Error in attachNamespace("org.Hs.eg.db") : namespace is already attached`

This is resolved if I unload the namespace by - `unloadNamespace("org.Hs.eg.db")`

Is this by design or a bug?

**Comment by BioSok** [comment]
It was a bug line of code that was re-attaching the namespace item. After the first run of the function it indeed gives that error. It is now fixed along with the "can't find data" warnings in that function. You can always find the current after-fix package in the Code tab.
