### ISSUE TITLE
Cannot load pcxn

### ISSUE THREAD

**Issue by wenbinwei** [hidelab/R-packages#2]
> install.packages("pcxn_0.99.0.tar.gz")
inferring 'repos = NULL' from 'pkgs'
* installing *source* package ‘pcxn’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (pcxn)
> library(pcxn)
Error in FUN(X[[i]], ...) : 
  cannot open file '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pcxn.db/data/Rdata.rdb': No such file or directory
In addition: Warning message:
In FUN(X[[i]], ...) : restarting interrupted promise evaluation

**Comment by BioSok** [comment]
Why does it try to open the pcxn.db package? Maybe you must remove the pcxn.db package first and then re-install the pcxn package.

**Comment by wenbinwei** [comment]
I removed pcxn.db but did not restart R. After restarting R, the issue is resolved.
