### ISSUE TITLE
could not find function "pcxn.gmembers" in R code from vignette source 'usingPCxNdb.Rnw'

### ISSUE THREAD

**Issue by wenbinwei** [hidelab/R-packages#3]
> gene_member_list <- pcxn.gmembers("Alzheimer's disease (KEGG)")
Error in pcxn.gmembers("Alzheimer's disease (KEGG)") : 
  could not find function "pcxn.gmembers"
>

**Comment by BioSok** [comment]
The function is called _pcxn.gene_members()_. Is it referenced in the documentation otherwise?

**Comment by BioSok** [comment]
I am sorry, just found that wrong reference in the vignette. Changing to the correct one.

**Comment by wenbinwei** [comment]
Please also change pcxn.db to pcxn in that document.

**Comment by BioSok** [comment]
All the above adressed and the current pcxn version is updated in Code tab.
