### ISSUE TITLE
heatmap scale can have fewer significant digits

### ISSUE THREAD

**Issue by wenbinwei** [hidelab/R-packages#4]
heatmap scale can have fewer significant digits. In the description of pcxn.heatmap, it would be better to add that "Color represents correlation coefficients."

**Comment by BioSok** [comment]
The package pheatmap does not offer the option to adjust the significat digits on the legend. Added the phrase in two separate pcxn.heatmap descriptions.

**Comment by wenbinwei** [comment]
I cannot see the added phrase. Have you committed your updated version?

**Comment by BioSok** [comment]
I will commit it tomorrow morning!
